[package]
name = "libphp"
version = "0.1.0"
edition = "2021"
license-file.workspace = true
rust-version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[build-dependencies]
bindgen = "0.69.4"
cc = "1.0.90"
